name: wallpaper_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.3
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  wallpaper_handler: ^0.0.2
  flutter_cache_manager: "^1.1.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.11
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
